# Linear Algebra - Matrices and Tensors

## 1. Scalar & Vectors

### . Scalar is a singel number
### . Vector ias an array of scalars 

In [2]:
import numpy as np

In [3]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)

print(x1[0])

[4 5 6]
(3,)
4


In [4]:
# We will represent a vector as a column vector, that is having multiple row

x = np.array([[4],[5],[6],[7]])

print(x)
print(x.shape)

print(x[0]) 

print(x[0][0])

[[4]
 [5]
 [6]
 [7]]
(4, 1)
[4]
4


In [5]:
# Reshaping

# x.reshape((no.of row ,no. of coloumn))

x = x.reshape((-1,2))
print(x)

[[4 5]
 [6 7]]


# 2. Matrices & Tensors

### . Matrices is a 2D array of scalars
### . Tensor is an array with more than 2 axes

In [6]:
# Here X is a Matrix

X= np.array([[4,5,6],[7,8,9],[1,2,3]])

print(X.shape)
print(X)

(3, 3)
[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [7]:
# Here T is Tensor

T = np.array([[[4,5,7],[10,11,13]],[[56,80,90],[9,8,10]]])

print(T.shape)

print(T)

print(T[1][1][1])

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]
8


In [8]:
# Here T is Tensor

T = np.array([[[4,5,7],[10,11,13]],[[56,80,90],[9,8,10]]])

print(T.shape)

print(T)

print(T[1][1][1])

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]
8


## 3. Transpose 

In [9]:
print(x)
xt = x
print(xt.transpose())

[[4 5]
 [6 7]]
[[4 6]
 [5 7]]


In [10]:
y = x.reshape((-1,1))

print(y)
print(y.shape)
print(y.transpose())

print(y.transpose().shape)

[[4]
 [5]
 [6]
 [7]]
(4, 1)
[[4 5 6 7]]
(1, 4)


## 4. Broadcasting


In [11]:
# Applying Broadcasting in array 

l = [1,2,3,4]
l = np.array(l)

l1=l+1

print(l1)

l2 = l**2

print(l2)

[2 3 4 5]
[ 1  4  9 16]


In [12]:
# Applying broadcasting in Matrix

lm = [[1,2,3],[4,5,6]]
lm = np.array(lm)

lm = lm**2

print(lm)

lm = lm+1
print(lm)

[[ 1  4  9]
 [16 25 36]]
[[ 2  5 10]
 [17 26 37]]


In [13]:
print(np.sqrt(lm))

[[1.41421356 2.23606798 3.16227766]
 [4.12310563 5.09901951 6.08276253]]


# 5. Matrix Multiplication

In [14]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[7,8],[9,10],[11,12]])

print(X.shape)
print(Y.shape)


print(X)
print(Y)

(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [15]:
prod = np.dot(X,Y)

print(prod.shape)

print(prod)

(2, 2)
[[ 58  64]
 [139 154]]


# 6. Element wise multiplication

In [17]:
X = np.array([[4,5,6],[7,8,9],[1,2,3]])

# np.eye(3) creates a identity matrix of 3x3 order
Y = np.eye(3)
print(X)

Y = Y*2
Y= Y +1 
print(Y)


[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


In [19]:
print(X*Y)

[[12.  5.  6.]
 [ 7. 24.  9.]
 [ 1.  2.  9.]]


# 7. Norm (Refer notes )

In [27]:
# x is a vector
x = np.array([-10,4,9])


# linalg => linear algebra , norm will return a normed func of vector x. By default the order of norm is 2
lp2 = np.linalg.norm(x)

print(lp2)

14.035668847618199


In [28]:
# ord => order , which puts the value of p as 1
lp1 = np.linalg.norm(x, ord = 1)

print(lp1)

23.0


In [31]:
# inf => infinity
# at infinity it returns the highest +ve or mode( |x| ) possible value present in vector

lp = np.linalg.norm(x,ord = np.inf)

print(lp)

10.0
